Release/1.0.2
iNZightVIT/Lite pull request #296
Opened 2023-02-19 07:46 UTC by chrk623

2023-02-19 19:27 UTC, tmelliott requested changes

2023-02-19 19:27 UTC, tmelliott commented on server.R
> +  values$lite.update = "20 February 2023"
This value should remain blank - it gets set in the VARS file, and written/modified at build time (i.e., in the Dockerfile). It won't affect the built version, but I'm not a fan of hard-coding values in an app like this.

2023-02-20 00:32 UTC, chrk623 commented on server.R
> +  values$lite.update = "20 February 2023"
Hey, check https://github.com/iNZightVIT/Lite/pull/296/commits/a96a1d4bca6c0a2e30f70598ef222a2928ee1de6.

2023-02-20 01:16 UTC, tmelliott commented on server.R
> +  values$lite.update = "20 February 2023"
It's OK to grab the version number from the DESCRIPTION file - I only meant the `lite.update` value (but GH decided to include both lines in my comment for some reason..) - sorry!

You also don't need to set the `lite.update` value in the `VARS.default` file (or anywhere) - it gets written at build time (in the Dockerfile), and if it's an empty string, the app doesn't print the date/version. You can test things by creating your own `VARS` file with test values - it gets ignored by git and won't get committed.

I hope that makes sense - let me know if you need further clarification!

2023-02-20 02:09 UTC, tmelliott commented on server.R
> +  values$lite.update = "20 February 2023"
Yes, that sounds about right. lite.version should pull from the DESCRIPTION, as you had initially.

2023-02-20 02:37 UTC, tmelliott approved these changes

2023-02-20 02:41 UTC, tmelliott commented
BTW, I've set up a Railway instance to track this branch - https://lite-staging.up.railway.app/

2023-02-20 05:29 UTC, chrk623 commented
Also fixed #297.

2023-02-20 08:54 UTC, tmelliott commented
Great - can you also add the VIT fix to NEWS.

2023-02-20 09:46 UTC, chrk623 commented
Oh forgot about it!
Should be good to go now.

2023-02-20 20:06 UTC, tmelliott commented
Great - I'm fine with this going live today. From here,

- create a new PR (release/1.0.2 -> dev)
- merge the current PR (#296) - the new docker image should build automatically (GitHub actions) and deploy *at some time* once the AWS automation picks it up
- merge the other PR (this branch back into dev) and delete this branch
- tag the master branch (`git checkout master`) with the version (`git tag 1.0.2`) and push (`git push --tags`) - I've copied a GH action to create a GH release from this tag automatically

and that should be everything.

2023-02-20 23:50 UTC, chrk623 commented
Hey what do you mean by *create a new PR (release/1.0.2 -> dev)*? This branch is already merging to dev.

I'll push the release after #298.

2023-02-21 01:52 UTC, tmelliott commented
Ah - sorry, missed that. For release branches, I usually create two PRs:
- release/x -> master (the main PR)
- release/x -> dev (to all finalised changes get merged back into dev)

This way, you can keep merging new changes into dev even after a release is started (once you start a release, you typically only make bug fixes and minor changes, like wording, etc.). Though, when it's just one person developing it's less of an issue..!

So, 
- create a new PR `release/1.0.2 -> master` - then merge that one first once it's checked and working, and *then* this one.

2023-02-21 01:59 UTC, tmelliott commented
Also - I think #298 might be a bit of work, so let's finish this release (and check the automations work nicely) and then start working on that.

2023-02-21 05:47 UTC, merged